version: '3'

services:
    postgres:
      container_name: "paasuke_postgres"
      image: postgres:9.6.19-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./tests/postgres-volume:/var/lib/postgresql/data/
        - ./tests/pg_data:/docker-entrypoint-initdb.d/
      ports:
        - 5432:5432
    provider_adapter_api:
      container_name: "paasuke_provider_adapter_api"
      build:
        context: .
        dockerfile: Dockerfile.provider_adapter_api
      depends_on:
        - postgres
      ports:
        - 5002:5000
      environment:
        FLASK_ENV: development
      volumes:
        - .:/app