version: '3'

services:
    postgres:
      container_name: "paasuke_postgres"
      image: postgres:9.6.19-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - ./postgres-volume:/var/lib/postgresql/data/
        - ./tests/pg_data:/docker-entrypoint-initdb.d/
      ports:
        - 5432:5432

