origin_url: http://example.com/
errors:
    legal_person_format_validation_failed:
      reference: http://example-legal-person-naming-guidence.com
      title: Legal person validation failed
      translation:
        en: Legal person validation does not match format
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-legal-person-validation
    representee_not_found:
      reference: http://example-representee-not-found-guidence.com
      title: Representee was not found
      translation:
        en: Representee was not found
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-representee-not-found
    delegate_not_found:
      reference: http://example-delegate-not-found-guidence.com
      title: Delegate was not found
      translation:
        en: Delegate was not found
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-delegate-not-found
    mandate_data_invalid:
      reference: http://example-mandate-data-invalid-guidence.com
      title: Mandate data is invalid
      translation:
        en: Mandate data is invalid
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-mandate-data-invalid
    mandate_subdelegate_data_invalid:
      reference: http://example-mandate-subdelegate-data-invalid-guidence.com
      title: Mandate subdelegate data is invalid
      translation:
        en: Mandate subdelegare data is invalid
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-mandate-subdelegate-data-invalid
    mandate_not_found:
      reference: http://example-mandate-not-found-guidence.com
      title: Mandate not found
      translation:
        en: Mandate not found
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-mandate-not-found
    internal_server_error:
      reference: http://example-internal-server-error-guidence.com
      title: Internal server error
      translation:
        en: Internal server error
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-internal-server-error-found
    unprocessable_request:
      reference: http://example-unprocessable-request-error-guidence.com
      title: Unprocessable request error
      translation:
        en: Unprocessable request error
        et: Volituse kustutamine ebaõnnestus
        ru: Volituse kustutamine ebaõnnestus (ru)
      type: test-type-for-internal-server-error-found
