version: "3.3"

services:
  ph-rolebinding-api-mock:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CATALINA_OPTS: -Dspring.profiles.active=docker
      MOCKS_DIR: /etc/mocks/
    ports:
      - "8081:8080"
    volumes:
      - ./mocks:/etc/mocks